CITIES = ['Brzeg Głogowski', 'Starogard Gdański', 'Pułtusk', 'Legionowo', 'Kędzierzyn-Koźle', 'Kętrzyn', 'Jędrzejów',
          'Trzebnica', 'Szczawno-Zdrój', 'Proszowice', 'Stalowa Wola', 'Jasło', 'Nidzica', 'Sokolec', 'Opole',
          'Jarczew', 'Nieszawa',
          'Tarnów', 'Szczawnica', 'Parzniewice', 'Gryfice', 'Sanok', 'Widuchowa', 'Bogatynia',
          'Ostrowiec Świętokrzyski', 'Kostrza',
          'Brześć Kujawski', 'Przemyśl', 'Międzyrzecz', 'Katowice', 'Korsze', 'Dorohusk', 'Sochaczew',
          'Międzyrzec Podlaski', 'Koszalin', 'Prudnik', 'Polańczyk', 'Krempna', 'Zamość', 'Kołuda Wielka', 'Andrychów',
          'Środa Śląska',
          'Chełmża', 'Częstochowa', 'Ostróda', 'Kamień Pomorski', 'Będzin', 'Żywiec', 'Glitajny', 'Chodecz',
          'Giżycko', 'Brodnica',
          'Mieczysławów', 'Kobierzyce', 'Niepołomice', 'Włodawa', 'Miasteczko Śląskie', 'Chełm', 'Żukowice', 'Kęty',
          'Ozorków', 'Świdnik',
          'Kutno', 'Iława', 'Żagań', 'Nowa Sól', 'Zambrów', 'Horyniec-Zdrój', 'Wadowice', 'Jasna Góra',
          'Ustrzyki Dolne', 'Szczytno', 'Czarna',
          'Sopot', 'Miechów', 'Gajew', 'Zielonka', 'Racibórz', 'Wąbrzeźno', 'Wolbrom', 'Konstancin-Jeziorna', 'Kielce',
          'Chojnów',
          'Golub-Dobrzyń', 'Pleszew', 'Grajewo', 'Maków Mazowiecki', 'Łęczna', 'Bielsk Podlaski', 'Opatów', 'Wieliczka',
          'Łeba',
          'Dobrzyń nad Wisłą', 'Lubaczów', 'Zameczno', 'Kłodzko', 'Białystok', 'Kartuzy', 'Dębno', 'Opoczno', 'Ełk',
          'Gubin', 'Końskie',
          'Mogilno', 'Kraśnik', 'Piotrkowice', 'Pruszków', 'Działoszyn', 'Skawina', 'Ruda Śląska', 'Sokołów Podlaski',
          'Gryfino', 'Cieszyn',
          'Siedlce', 'Łowicz', 'Czerwionka-Leszczyny', 'Iwonicz-Zdrój', 'Władysławowo', 'Rybnik', 'Nowy Tomyśl',
          'Bielawa', 'Złotoryja', 'Krotoszyn', 'Borucin', 'Kołobrzeg', 'Wałcz', 'Radomsko', 'Górne Gruczno', 'Lubań',
          'Piastów',
          'Gorzów Wielkopolski', 'Przysiek', 'Świecie', 'Sokółka', 'Szczecin', 'Mława', 'Bolesławiec', 'Dzierżoniów',
          'Szklarska Poręba',
          'Borówiec', 'Połaniec', 'Gostynin', 'Słupsk', 'Dąbrowa Górnicza', 'Żyrardów', 'Nowy Targ', 'Siemiatycze',
          'Komańcza', 'Wiktorowo',
          'Kwidzyn', 'Szamotuły', 'Turek', 'Czarna Góra', 'Sierpc', 'Grodzisk Mazowiecki', 'Toruń',
          'Piotrków Trybunalski', 'Myszków', 'Luboń',
          'Dębica', 'Kruszyn', 'Ostrołęka', 'Radom', 'Kraków', 'Swarzędz', 'Tychy', 'Kolbuszowa', 'Szczecinek',
          'Szklarki', 'Czarny Las',
          'Jaworzno', 'Tuchola', 'Ząbkowice Śląskie', 'Mińsk Mazowiecki', 'Głubczyce', 'Mszana Dolna', 'Legnica',
          'Wałbrzych',
          'Piechcin', 'Belsk Duży', 'Świebodzin', 'Namysłów', 'Drezdenko', 'Białka', 'Olkusz', 'Lądek-Zdrój', 'Spalona',
          'Sobczyce',
          'Ostrów Mazowiecka', 'Grodziec Mały', 'Wyszków', 'Lubin', 'Koniczynka', 'Radomierzyce', 'Konin', 'Gostyń',
          'Bydgoszcz', 'Chęciny',
          'Słone', 'Nałęczów', 'Świnoujście', 'Gać', 'Malbork', 'Tuchów', 'Tarnobrzeg', 'Wejherowo', 'Jarocin',
          'Rabka-Zdrój', 'Kawice', 'Biała',
          'Brzeziny', 'Rawa Mazowiecka', 'Oborniki', 'Duszniki-Zdrój', 'Oława', 'Sandomierz', 'Busko-Zdrój', 'Wołomin',
          'Witków', 'Zawiercie',
          'Poznań', 'Krzyżówka', 'Przeworsk', 'Płońsk', 'Sulęcin', 'Oświęcim', 'Dąbrowa Tarnowska', 'Warszawa',
          'Łuków',
          'Polanica-Zdrój', 'Głogówko', 'Mielec', 'Lesko', 'Osieczów', 'Chełmno', 'Stargard Szczeciński',
          'Tarnowo Podgórne', 'Jeleniów', 'Lublin',
          'Wolice', 'Limanowa', 'Piła', 'Kowary', 'Marwice', 'Łasin', 'Trzcianka', 'Latoszyn', 'Muszyna',
          'Ustka', 'Jastrzębie-Zdrój',
          'Leśna', 'Izbica Kujawska', 'Odolanów', 'Kozienice', 'Hajnówka', 'Augustów', 'Rzeszów', 'Goczałkowice-Zdrój',
          'Brzeszcze', 'Gołdap', 'Grab', 'Jelenia Góra', 'Liniewko Kościerskie', 'Biłgoraj', 'Szczebrzeszyn',
          'Myślibórz',
          'Głogów', 'Nakło nad Notecią', 'Wodzisław Śląski', 'Lipnik', 'Słubice', 'Słomniki', 'Wieluń', 'Złoczew',
          'Kruszwica',
          'Stare Koźle', 'Nowiny', 'Grudziądz', 'Żory', 'Strzelin', 'Karpacz', 'Kozie Doły', 'Pabianice',
          'Skarżysko-Kamienna',
          'Kościerzyna', 'Mosina', 'Kłobuck', 'Aleksandrów Kujawski', 'Ożarów', 'Godów', 'Sosnowiec', 'Gdynia',
          'Inowrocław', 'Sępólno Krajeńskie',
          'Nowe Skalmierzyce', 'Koło', 'Bielsko-Biała', 'Ciechanów', 'Ciechocinek', 'Gorlice', 'Tarnowskie Góry',
          'Myślenice', 'Nowa Ruda', 'Puławy',
          'Rypin', 'Ostrów Wielkopolski', 'Maszewo Duże', 'Święty Krzyż', 'Elbląg', 'Jawor', 'Chrzanów', 'Lubliniec',
          'Zgierz', 'Sadłogoszcz', 'Chorzów',
          'Pionki', 'Krosno', 'Małogoszcz', 'Nisko', 'Sieradz', 'Zabrze', 'Kościan', 'Milicz', 'Krzeszowice', 'Złockie',
          'Mrągowo', 'Gliwice', 'Dobczyce', 'Wrocław', 'Biała Podlaska', 'Leszno', 'Tczew', 'Łask', 'Zakopane',
          'Zduńska Wola', 'Płock', 'Łomża',
          'Złoty Potok', 'Krynica-Zdrój', 'Szymbark', 'Kalisz', 'Olesno', 'Opatówek', 'Trzebinia', 'Olsztyn',
          'Nowy Sącz', 'Polkowice', 'Wieniec-Zdrój',
          'Otwock', 'Aleksandrów Łódzki', 'Rawicz', 'Radziejów', 'Brzeg', 'Bełchatów', 'Szarów', 'Łódź',
          'Rymanów-Zdrój', 'Ustroń',
          'Gdańsk', 'Wleń', 'Żnin', 'Białe Błota', 'Starachowice', 'Strzelce Opolskie', 'Zdzieszowice', 'Hrubieszów',
          'Skierniewice', 'Piekary Śląskie',
          'Wągrowiec', 'Bytom', 'Wilczopole', 'Uniejów', 'Kromolin', 'Zabierzów', 'Radzyń Chełmiński',
          'Nowa Wies Wielka', 'Pajęczno',
          'Wschowa', 'Nysa', 'Krasnobród', 'Bukowno', 'Gniezno', 'Tomaszów Lubelski', 'Sucha Beskidzka', 'Włocławek',
          'Wojkowice', 'Gołuchów', 'Nowy Dwór Mazowiecki', 'Kamienna Góra', 'Świdnica', 'Chojnice', 'Września',
          'Tłuszcz',
          'Maków Podhalański', 'Kaszów', 'Koziegłowy', 'Kudowa-Zdrój', 'Kalwaria Zebrzydowska', 'Radzyń Podlaski',
          'Piaseczno', 'Krasnystaw',
          'Pruszcz Gdański', 'Biskupiec', 'Knurów', 'Działdowo', 'Brzesko', 'Storkowo', 'Kluczbork', 'Chodzież',
          'Borsukowizna', 'Oleśnica',
          'Stoki', 'Gorzyce', 'Krynica', 'Adamów', 'Florianka', 'Rejowiec Fabryczny', 'Suwałki', 'Jedlina-Zdrój',
          'Guty Duże', 'Przerzeczyn-Zdrój',
          'Police', 'Solec Kujawski', 'Januszkowice', 'Bartoszyce', 'Bochnia', 'Trzepowo', 'Połczyn-Zdrój',
          'Zgorzelec', 'Lębork', 'Pszczyna', 'Tomaszów Mazowiecki', 'Żary', 'Zielona Góra', 'Lwówek Śląski', 'Goleniów']