province = {'piaseczeński': ['Konstancin-Jeziorna', 'Piaseczno'], 'radomski': 'Pionki', 'sierpecki': 'Sierpc',
            'gostyniński': 'Gostynin', 'grodzisk': 'Grodzisk Mazowiecki', 'łukowski': ['Łuków', 'Adamów', 'Jarczew'],
            'Chełm': 'Chełm', 'brzeski': ['Brzesko', 'Brzeg'], 'Kraków': 'Kraków',
            'zgierski': ['Ozorków', 'Aleksandrów Łódzki', 'Zgierz'], 'sulęciński': 'Sulęcin', 'Radom': 'Radom',
            'żyrardowski': ['Krzyżówka', 'Żyrardów'], 'obornicki': 'Oborniki', 'Siedlce': 'Siedlce', 'Leszno': 'Leszno',
            'kolski': 'Koło', 'Łomża': 'Łomża', 'rawicki': 'Rawicz', 'kościerski': ['Kościerzyna', 'Liniewko Kościerskie'],
            'stargardzki': 'Stargard Szczeciński', 'Wrocław': 'Wrocław', 'giżycki': ['Giżycko', 'Gajew'], 'mrągowski': 'Mrągowo',
            'głogowski': ['Kromolin', 'Brzeg Głogowski', 'Zameczno', 'Żukowice', 'Kozie Doły', 'Głogówko', 'Sobczyce', 'Grodziec Mały', 'Głogów'],
            'Sosnowiec': 'Sosnowiec', 'rybnicki': 'Czerwionka-Leszczyny', 'Gliwice': 'Gliwice', 'Piekary Śląskie': 'Piekary Śląskie',
            'Jaworzno': 'Jaworzno', 'inowrocławski': ['Inowrocław', 'Kruszwica', 'Kołuda Wielka'], 'brodnicki': ['Brodnica'],
            'włocławski': ['Wieniec-Zdrój', 'Brześć Kujawski', 'Izbica Kujawska', 'Chodecz'], 'mogileński': 'Mogilno',
            'Toruń': 'Toruń', 'tucholski': 'Tuchola', 'raciborski': ['Borucin', 'Racibórz'], 'cieszyński': ['Cieszyn', 'Ustroń'],
            'nyski': 'Nysa', 'Jelenia Góra': 'Jelenia Góra', 'zgorzelecki': ['Zgorzelec', 'Radomierzyce', 'Bogatynia', 'Jasna Góra'],
            'Ostrołęka': 'Ostrołęka', 'jarociński': 'Jarocin', 'Gdynia': 'Gdynia', 'Świnoujście': 'Świnoujście',
            'kamiennogórski': 'Kamienna Góra', 'pabianicki': 'Pabianice', 'ostródzki': 'Ostróda', 'Przemyśl': 'Przemyśl',
            'włodawski': 'Włodawa', 'bocheński': 'Bochnia', 'Tarnów': 'Tarnów', 'wschowski': 'Wschowa', 'międzyrzecki': ['Międzyrzecz', 'Stoki', 'Nowiny'],
            'słubicki': 'Słubice', 'nowotomyski': 'Nowy Tomyśl', 'wągrowiecki': 'Wągrowiec', 'słupski': 'Ustka',
            'ostrowiecki': 'Ostrowiec Świętokrzyski', 'skarżyski': 'Skarżysko-Kamienna', 'kartuski': ['Szymbark', 'Kartuzy'],
            'częstochowski': 'Złoty Potok', 'Elbląg': 'Elbląg', 'gryfiński': ['Gryfino', 'Marwice', 'Widuchowa'], 'Bytom': 'Bytom',
            'złotoryjski': 'Złotoryja', 'wrocławski': 'Kobierzyce', 'milicki': 'Milicz', 'lubiński': 'Lubin', 'lipnowski': 'Dobrzyń nad Wisłą',
            'żniński': ['Żnin', 'Wolice', 'Sadłogoszcz', 'Piechcin'], 'radziejowski': 'Radziejów', 'nakielski': 'Nakło nad Notecią',
            'bartoszycki': 'Bartoszyce', 'żywiecki': 'Żywiec', 'sokolski': ['Sokółka', 'Borsukowizna'], 'jasielski': ['Jasło', 'Krempna'],
            'głubczycki': 'Głubczyce', 'nowosądecki': ['Krynica', 'Złockie', 'Muszyna', 'Krynica-Zdrój'], 'Zielona Góra': ['Zielona Góra', 'Jeleniów'],
            'Skierniewice': 'Skierniewice', 'żagański': ['Żagań', 'Witków'], 'Gdańsk': 'Gdańsk', 'lęborski': ['Łeba', 'Lębork'],
            'piotrkowski': ['Parzniewice', 'Łódź'], 'starogardzki': 'Starogard Gdański',
            'Poznań': 'Poznań', 'Konin': 'Konin', 'Tarnobrzeg': 'Tarnobrzeg', 'płoński': 'Płońsk', 'mławski': 'Mława',
            'hrubieszowski': 'Hrubieszów', 'kraśnicki': 'Kraśnik', 'łęczyński': 'Łęczna', 'Zamość': 'Zamość', 'dąbrowski': 'Dąbrowa Tarnowska',
            'krakowski': ['Skawina', 'Kaszów', 'Zabierzów', 'Krzeszowice', 'Słomniki'], 'żarski': 'Żary', 'krośnieński': ['Iwonicz-Zdrój', 'Rymanów-Zdrój', 'Gubin'],
            'dębicki': ['Czarna', 'Latoszyn', 'Dębica'], 'namysłowski': 'Namysłów', 'czarnkowsko-trzcianecki': 'Trzcianka',
            'Płock': 'Płock', 'grajewski': 'Grajewo', 'starachowicki': 'Starachowice', 'konecki': 'Końskie', 'nidzicki': 'Nidzica',
            'Ruda Śląska': 'Ruda Śląska', 'tarnogórski': ['Miasteczko Śląskie', 'Tarnowskie Góry'], 'zawierciański': 'Zawiercie',
            'Chorzów': 'Chorzów', 'Katowice': 'Katowice', 'bolesławiecki': ['Osieczów', 'Bolesławiec'], 'Wałbrzych': ['Wałbrzych', 'Szczawno-Zdrój'],
            'sępoleński': 'Sępólno Krajeńskie', 'Włocławek': 'Włocławek', 'hajnowski': 'Hajnówka', 'chrzanowski': ['Chrzanów', 'Trzebinia'],
            'wejherowski': 'Wejherowo', 'Szczecin': 'Szczecin', 'pucki': 'Władysławowo', 'rawski': 'Rawa Mazowiecka', 'łowicki': 'Łowicz',
            'iławski': 'Iława', 'niżański': 'Nisko', 'tarnobrzeski': 'Gorzyce', 'pruszkowski': ['Pruszków', 'Piastów'],
            'wyszkowski': 'Wyszków', 'biłgorajski': ['Biłgoraj', 'Florianka'], 'chełmski': ['Rejowiec Fabryczny', 'Dorohusk'],
            'świdnicki': ['Kostrza', 'Świdnica', 'Świdnik'], 'kutnowski': 'Kutno', 'kolbuszowski': 'Kolbuszowa', 'oleski': 'Olesno',
            'strzelecki': 'Strzelce Opolskie', 'Suwałki': 'Suwałki', 'kościański': ['Piotrkowice', 'Kościan'], 'szamotulski': 'Szamotuły',
            'Kielce': 'Kielce', 'staszowski': 'Połaniec', 'ełcki': 'Ełk', 'dzierżanowski': ['Dzierżoniów', 'Bielawa', 'Przerzeczyn-Zdrój'],
            'tczewski': 'Tczew', 'kołobrzeski': 'Kołobrzeg', 'Koszalin': 'Koszalin', 'kłobucki': 'Kłobuck', 'gliwicki': 'Knurów',
            'lubliniecki': 'Lubliniec', 'Bielsko-Biała': 'Bielsko-Biała', 'Legnica': 'Legnica', 'grudziądzki': ['Łasin', 'Radzyń Chełmiński', 'Wiktorowo'],
            'toruński': ['Chełmża', 'Koniczynka', 'Przysiek'], 'chełmiński': 'Chełmno', 'wodzisławski': ['Wodzisław Śląski', 'Godów'],
            'leski': ['Lesko', 'Polańczyk'], 'bieszczadzki': 'Ustrzyki Dolne', 'prudnicki': ['Prudnik', 'Biała'], 'ząbkowicki': 'Ząbkowice Śląskie',
            'makowski': ['Maków Mazowiecki', 'Guty Duże'], 'pszczyński': ['Goczałkowice-Zdrój', 'Pszczyna'], 'gołdapski': 'Gołdap',
            'Sopot': 'Sopot', 'jeleniogórski': ['Szklarska Poręba', 'Karpacz', 'Kowary'], 'opoczyński': 'Opoczno',
            'ostrowski': ['Odolanów', 'Ostrów Wielkopolski', 'Nowe Skalmierzyce', 'Ostrów Mazowiecka'], 'Kalisz': 'Kalisz', 'miński': 'Mińsk Mazowiecki',
            'zwoleński': 'Mieczysławów', 'lubelski': 'Wilczopole', 'proszowicki': 'Proszowice', 'wielicki': ['Wieliczka', 'Niepołomice', 'Szarów'],
            'sieradzki': ['Sieradz', 'Złoczew'], 'brzeziński': 'Brzeziny', 'strzelecko-drezdenecki': 'Drezdenko', 'świebodziński': 'Świebodzin',
            'lubaczowski': ['Lubaczów', 'Horyniec-Zdrój'], 'chodzieski': 'Chodzież', 'kluczborski': 'Kluczbork', 'jędrzejewski': ['Jędrzejów', 'Małogoszcz'],
            'gostyniński': 'Gostynin', 'kaliski': 'Opatówek', 'siemiatycki': 'Siemiatycze', 'gdański': ['Pruszcz Gdański', 'Trzepowo'],
            'szczycieński': 'Szczytno', 'gryficki': 'Gryfice', 'myszkowski': ['Myszków', 'Koziegłowy'], 'oleśnicki': 'Oleśnica',
            'strzeliński': 'Strzelin', 'wąbrzeski': 'Wąbrzeźno', 'kętrzyński': ['Kętrzyn', 'Korsze', 'Glitajny',], 'augustowski': ['Augustów', 'Czarny Las'],
            'wałbrzyski': 'Jedlina-Zdrój', 'kłodzki': ['Sokolec', 'Nowa Ruda', 'Kudowa-Zdrój', 'Duszniki-Zdrój', 'Polanica-Zdrój', 'Kłodzko', 'Spalona', 'Lądek-Zdrój'],
            'Tychy': 'Tychy', 'Rybnik': 'Rybnik', 'sokołowski': 'Sokołów Podlaski', 'grójecki': 'Belsk Duży',
            'puławski': ['Puławy', 'Nałęczów'], 'radzyński': 'Radzyń Podlaski', 'Biała Podlaska': 'Biała Podlaska', 'Nowy Sącz': 'Nowy Sącz',
            'Gorzów Wielkopolski': 'Gorzów Wielkopolski', 'pilski': 'Piła', 'buski': 'Busko-Zdrój', 'turecki': 'Turek',
            'opatowski': ['Opatów', 'Ożarów'], 'Słupsk': 'Słupsk', 'bielski': 'Bielsk Podlaski', 'polkowicki': ['Szklarki', 'Polkowice'],
            'Jastrzębie-Zdrój' : 'Jastrzębie-Zdrój', 'tatrzański': ['Czarna Góra', 'Zakopane'], 'nowotarski': ['Rabka-Zdrój', 'Nowy Targ', 'Szczawnica'],
            'lwówecki': ['Lwówek Śląski', 'Wleń'], 'legionowski': 'Legionowo', 'tomaszowski': ['Tomaszów Lubelski', 'Tomaszów Mazowiecki'], 'zambrowski': 'Zambrów',
            'płocki': 'Maszewo Duże', 'pułtuski': 'Pułtusk', 'sochaczewski': 'Sochaczew', 'ciechanowski': 'Ciechanów',
            'bialski': 'Międzyrzec Podlaski', 'krasnostawski': ['Krasnystaw', 'Lublin'], 'zamojski': ['Krasnobród', 'Szczebrzeszyn'],
            'tarnowski': 'Tuchów', 'bełchatowski': 'Bełchatów', 'łaski': 'Łask', 'pajęczański': ['Działoszyn', 'Pajęczno'],
            'radomszczański': 'Radomsko', 'zduńskowolski': 'Zduńska Wola', 'nowosolski': 'Nowa Sól', 'mielecki': 'Mielec',
            'Warszawa': 'Warszawa', 'krapkowicki': ['Opole', 'Zdzieszowice', 'Januszkowice'], 'moniecki': 'Kruszyn',
            'kielecki': ['Święty Krzyż', 'Chęciny'], 'wrzesiński': 'Września', 'gnieźnieński': 'Gniezno', 'malborski': 'Malbork',
            'olsztyński': 'Biskupiec', 'działdowski': 'Działdowo', 'kwidzyński': 'Kwidzyn', 'Dąbrowa Górnicza': 'Dąbrowa Górnicza',
            'myśliborski': ['Dębno', 'Myślibórz'], 'golubsko-dobrzyński': 'Golub-Dobrzyń', 'aleksandrowski': ['Nieszawa', 'Ciechocinek', 'Aleksandrów Kujawski'],
            'świecki': ['Świecie', 'Górne Gruczno'], 'pleszewski': ['Pleszew', 'Gołuchów', 'Grab'], 'Krosno': 'Krosno',
            'sanocki': ['Sanok', 'Komańcza'], 'suski': ['Sucha Beskidzka', 'Maków Podhalański', 'Białka'], 'zielonogórski': 'Słone',
            'wołomiński': ['Tłuszcz', 'Wołomin', 'Zielonka'], 'goleniowski': 'Goleniów', 'Rzeszów': 'Rzeszów', 'wałecki': 'Wałcz',
            'chojnicki': 'Chojnice', 'przeworski': ['Gać', 'Przeworsk'], 'otwocki': 'Otwock', 'kozienicki': 'Kozienice',
            'limanowski': ['Mszana Dolna', 'Limanowa'], 'miechowski': 'Miechów', 'myślenicki': ['Myślenice', 'Dobczyce', 'Lipnik'],
            'olkuski': ['Bukowno', 'Olkusz', 'Wolbrom'], 'oświęcimski': ['Oświęcim', 'Brzeszcze', 'Kęty'], 'Piotrków Trybunalski': 'Piotrków Trybunalski',
            'poddębicki': 'Uniejów', 'wieluński': 'Wieluń', 'kędzierzyńsko-kozielki': ['Stare Koźle', 'Kędzierzyn-Koźle'], 'krotoszyński': 'Krotoszyn',
            'Białystok': 'Białystok', 'sandomierski': 'Sandomierz', 'szczecinecki': ['Storkowo', 'Szczecinek'], 'świdwiński': 'Połczyn-Zdrój',
            'Zabrze': 'Zabrze', 'Olsztyn': 'Olsztyn', 'kamieński': 'Kamień Pomorski', 'Częstochowa': 'Częstochowa', 'trzebnicki': 'Trzebnica',
            'bydgoski': ['Nowa Wies Wielka', 'Solec Kujawski', 'Białe Błota'], 'oławski': 'Oława', 'średzki': 'Środa Śląska',
            'legnicki': ['Kawice', 'Chojnów'], 'Bydgoszcz': 'Bydgoszcz', 'Grudziądz': 'Grudziądz', 'rypiński': 'Rypin', 'gorlicki': 'Gorlice',
            'lubański': ['Lubań', 'Leśna'], 'wadowicki': ['Andrychów', 'Wadowice', 'Kalwaria Zebrzydowska'], 'Żory': 'Żory',
            'nowodworski': ['Nowy Dwór Mazowiecki'], 'jaworski': 'Jawor', 'poznański':['Tarnowo Podgórne', 'Mosina', 'Borówiec', 'Luboń', 'Swarzędz'],
            'stalowowolski': 'Stalowa Wola', 'będziński': ['Będzin', 'Wojkowice'], 'policki': 'Police', 'gostyński': 'Gostyń',
            }